services:
  db:
    image: postgres:16-alpine
    container_name: vocab_db
    environment:
      POSTGRES_USER: vocab_user
      POSTGRES_PASSWORD: vocab_password
      POSTGRES_DB: vocab_db
    ports:
      - "5432:5432"
    volumes:
      - /srv/vocab/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vocab_user -d vocab_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: vocab_backend
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: vocab_user
      POSTGRES_PASSWORD: vocab_password
      POSTGRES_DB: vocab_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    container_name: vocab_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - pnpm-store:/pnpm-store
      - node-modules:/app/node_modules
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  pnpm-store:
  node-modules:
